config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/github/callback' => 'sessions#create', via: [:get, :post]

  root to: 'static#home'
  get '/rules' => 'static#rules', as: 'rules'
  get '/admin' => 'admin#index'
  namespace "admin" do
    resources :categories
    resources :boards
    resources :static_pages, only: [:index, :edit, :update], param: :slug
    resources :users, only: [:index, :update], param: :slug
  end
  resources :boards, only: [:index, :show]
  resources :board_threads, only: [:show, :new, :create, :edit, :update, :destroy], :path => "threads"  do
    resources :posts, except: [:update]
    patch '/posts' => 'posts#update'
  end
  resources :users, param: :slug
  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  post '/session' => 'sessions#create', as: 'session'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/threads/:board_thread_id/lock' => 'board_threads#lock', as: 'lock'
  post '/karma' => 'users#karma', as: 'karma'
  post '/ban' => 'users#banned', as: 'banned'
  post '/search' => 'board_threads#search'

end

app/models/board_thread.rb
class BoardThread < ApplicationRecord
    scope :with_long_title, -> {where("LENGTH(title) > 20")}
    validates_presence_of :title

    has_many :posts, dependent: :destroy
    has_many :users, through: :posts
    belongs_to :board

    accepts_nested_attributes_for :posts

end

app/controllers/board_threads_controller.rb
class BoardThreadsController < ApplicationController
    before_action :redirect_if_logged_out
    def new
        @board = Board.find_by_id(params[:board_id])
        session[:board_id] = @board.id
        @board_thread = @board.board_threads.build
        @board_thread.posts.build
    end

    def create
        @board = Board.find_by_id(session[:board_id])
        session.delete(:board_id)
        @board_thread = @board.board_threads.build(board_thread_params)
        if @board_thread.save
            flash.notice = "Thread successfully created!"
            redirect_to board_thread_path(@board_thread)
        else
            render 'new'
        end
    end

    def edit
        require_admin
        @boards = Board.all
        @board_thread = BoardThread.find_by_id(params[:id])
        @board = @board_thread.board
    end

    def update
        require_admin
        @board_thread = BoardThread.find_by_id(params[:id])
        if @board_thread.update(board_thread_params)
            flash.notice = "Thread successfully moved!"
            redirect_to board_thread_path(@board_thread)
        else
            flash.notice = "Invalid Board Selected, reverting changes."
            redirect_to board_thread_path(@board_thread)
        end
    end

    def show
        if params[:q]
            @board_thread = BoardThread.find_by_id(params[:id])
            user = User.find_by(username: params[:q])
            search_query(user)
        else
            @board_thread = BoardThread.find_by_id(params[:id])
            @posts = @board_thread.posts unless @board_thread.posts.empty?
        end
    end

    def destroy
        board_thread = BoardThread.find_by_id(params[:id])
        board = board_thread.board
        if admin?
            board_thread.delete
            flash.notice = "Thread deleted!"
            redirect_to board_path(board) and return
        end
        redirect_to board_path(board) and return
    end

    def lock
        swap_lock
    end

    private

    def board_thread_params
        params.require(:board_thread).permit(:title, :board_id, posts_attributes: [
            :content,
            :board_thread_id,
            :user_id
        ])
    end

    def swap_lock
        @board_thread = BoardThread.find_by_id(params[:board_thread_id])
        if admin?    
            @board_thread.locked = !@board_thread.locked
            @board_thread.save
        end
        redirect_to board_thread_path(@board_thread)
    end

    def search_query(user)
        if user
            flash.notice = "Showing Posts by #{user.username}."
            @posts = Post.where("user_id = ? AND board_thread_id = ?", user.id, @board_thread.id)
            if @posts.empty?
                flash.now.notice = "#{user.username} has not posted in this thread."
                @posts = @board_thread.posts
            end
        else
            if !params[:q].blank?
                flash.now.notice = "No users named #{params[:q]}."
            end
            @posts = @board_thread.posts
        end
    end

end

app/helpers/board_threads_helper.rb
module BoardThreadsHelper

    def lock_status(thread)
        if thread.locked
            "Locked"
        else
            "Unlocked"
        end
    end

    def locked_image(thread)
        if thread.locked
            "http://tinyimg.io/i/EbCgeyb.png"
        else
            "http://tinyimg.io/i/S6KNI1M.png"
        end
    end

    def thread_errors_display(board_thread, field)
        if board_thread.errors["#{field}"].any?
            info = tag.div board_thread.errors.full_messages_for("#{field}").join("<br>").html_safe, class: "errors_list"  
        end
    end

    def created_or_updated_time(post)
        if post.created_at == post.updated_at
            "Posted #{display_full_date_time(post.created_at)}"
        else
            "Updated #{display_full_date_time(post.updated_at)}"
        end
    end
end

app/views/board_threads/edit.html.erb
<div class="nav_path">PATH: <%= link_to @board.category.title, boards_path, :class => 'links' %> >> <%= link_to @board.title, board_path(@board), :class => 'links' %> >> <%= link_to 'Move Thread', edit_board_thread_path(board_id: @board), :class => 'links' %></div>

<div class="main_header">
    Move Thread
</div>

<%= form_for @board_thread, :html => {class: 'form'} do |f| %>
    <br>
    <div class="indent">
        <%= thread_errors_display(@board_thread, :title) %>
        <h2>Change Thread Location?</h2>
        <%= f.collection_select :board_id, @boards, :id, :title, {include_blank: 'Select A Board'},:class => 'select-css' %><br>
        <%= f.submit "", :class => "move_thread_button" %>
    </div>
<% end %>

app/views/board_threads/new.html.erb
<div class="nav_path">PATH: <%= link_to @board.category.title, boards_path, :class => 'links' %> >> <%= link_to @board.title, board_path(@board), :class => 'links' %> >> <%= link_to 'New Thread', new_board_thread_path(board_id: @board), :class => 'links' %></div>
<div class="main_header">
    New Thread
</div>

<%= form_for @board_thread, :html => {class: 'form'} do |f| %>
    <br>
    <div class="indent">
        <%= thread_errors_display(@board_thread, :title) %>
    </div>
    <div class="form_input_bg">
        <%= f.text_field :title, :placeholder => "Title", :class => 'form_input_field', :style => 'font-size: xx-large;' %>
    </div>
    <br>
    <%= f.fields_for :posts do |pf| %>
        <%= pf.label 'Post', :class => 'indent' %>
        <div class="indent">
            <%= thread_errors_display(@board_thread, "posts.content") %>
        </div>
        <%= pf.text_area :content, rows: 10, cols: 60, :class => 'reply_field', :placeholder => 'Initial Post' %>
        <%= pf.hidden_field :user_id, value: current_user.id %>
    <% end %>
    <%= f.hidden_field :board_id, value: @board.id %>
    <%= f.submit "", :class => "create_thread_button" %>
<% end %>

app/views/board_threads/show.html.erb
<div class="forum_tile">
    <%= form_tag board_thread_path(@board_thread), method: "GET" do %>
        <%= label_tag "Search Thread by User:", nil, :class => "post_link" %>
        <%= text_field_tag :q, nil, :class => "search_input_field" %>
        <%= hidden_field_tag :id, @board_thread.id %>
        <%= submit_tag "Search", :class => "search_button" %>
    <% end %>
</div>






<div class="nav_path">PATH: <%= link_to @board_thread.board.category.title, boards_path, :class => 'links' %> >> <%= link_to @board_thread.board.title, board_path(@board_thread.board), :class => 'links' %> >> <%= link_to friendly_title(@board_thread), board_thread_path(@board_thread), :class => 'links' %></div>

<div class="main_header">
    <%= "[LOCKED]" if @board_thread.locked  %><%= @board_thread.title %>
    <div class='locking'>
        <% if admin? %>
                <%= link_to image_tag("#{locked_image(@board_thread)}"), lock_path(@board_thread)%>
        <% end %>
    </div>
</div>
<div class="container">
<% @posts.each do |p| %>
    <div class="row">
        <div class="left">
            <%= p.user.display_avatar %>
            <%= link_to p.poster_username, user_path(p.poster_username), :class => 'post_link' %><br>
            Posts: <%= p.user.posts.count %><br>
            Karma: <%= p.user.karma %>
        </div>
        <div class="middle">
        <div class="button_align_right">
            <% if p.user == current_user || admin? %>
                <%= link_to "Edit", edit_board_thread_post_path(p.board_thread, p), :class => 'post_link', :method => :get  %> | <%= link_to "Delete", board_thread_post_path(p.board_thread, p), :class => 'post_link', data: {confirm: "This action is irreversible. Are you sure you want to delete this post?"}, :method => :delete %> | 
            <% end %>
            <%= link_to "Quote", new_board_thread_post_path(p.board_thread, p, params: {quote: {content: line_breaks(p.content), poster: p.user.username, timestamp: p.created_at}}), :class => 'post_link'%>
        </div>
        <p><%= line_breaks(p.content) %></p>
        <div class="timestamp"><%= created_or_updated_time(p)%></div>
        </div>
    </div>
<% end %>
</div>

<% if !@board_thread.locked %>
    <div class="innerwrapper">
        <div class="forum">
            <div class="forum_bod">
                <div class="quick_reply_header">
                    Quick Reply
                </div>
                <center>
                <%= form_for @board_thread.posts.build, :html => {class: 'forms'}, :url => board_thread_posts_path(@board_thread) do |f| %>
                    <%= f.text_area :content, cols: 180, rows: 10, :class => 'reply_field', :placeholder => "Make a new post . . ." %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :board_thread_id, value: @board_thread.id %><br>
                    <%= f.submit "", :class => 'quick_reply_button'%>
                <% end %>
                </center>
                <hr>
                <div class="centered_button"><%= button_to "", new_board_thread_post_path(board_thread_id: params[:id]), :class => "reply_button", :method => :get %></div>
            </div>
        </div>
    </div>
<% end %>