config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/github/callback' => 'sessions#create', via: [:get, :post]

  root to: 'static#home'
  get '/rules' => 'static#rules', as: 'rules'
  get '/admin' => 'admin#index'
  namespace "admin" do
    resources :categories
    resources :boards
    resources :static_pages, only: [:index, :edit, :update], param: :slug
    resources :users, only: [:index, :update], param: :slug
  end
  resources :boards, only: [:index, :show]
  resources :board_threads, only: [:show, :new, :create, :edit, :update, :destroy], :path => "threads"  do
    resources :posts, except: [:update]
    patch '/posts' => 'posts#update'
  end
  resources :users, param: :slug
  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  post '/session' => 'sessions#create', as: 'session'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/threads/:board_thread_id/lock' => 'board_threads#lock', as: 'lock'
  post '/karma' => 'users#karma', as: 'karma'
  post '/ban' => 'users#banned', as: 'banned'
  post '/search' => 'board_threads#search'

end

app/models/board.rb
class Board < ApplicationRecord
    validates :title, :presence => true,
                      :uniqueness => true
    
    validates_presence_of :category_id


    has_many :board_threads, dependent: :destroy
    has_many :posts, through: :board_threads
    belongs_to :category
    
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < AdminController
  
    def index
        @boards = Board.all
    end

    def new
        @board = Board.new
        @categories = Category.all
    end

    def create
        @board = Board.new(board_params)
        if @board.save
            flash.notice = "Board successfully created!"
            redirect_to admin_boards_path
        else
            @categories = Category.all
            render 'new'
        end
    end

    def edit
        @board = Board.find_by_id(params[:id])
        @categories = Category.all
    end

    def update
        @board = Board.find_by_id(params[:id])
        if @board.update(board_params)
            flash.notice = "Board successfully updated!"
            redirect_to admin_boards_path
        else
            @categories = Category.all
            render 'edit'
        end
    end

    def destroy
        board = Board.find_by_id(params[:id])
        board.delete

        flash.notice = "Board deleted!"
        redirect_to admin_boards_path
    end

    private

    def board_params
        params.require(:board).permit(:title, :category_id, :description)
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :redirect_if_logged_out
    def index
        @categories = Category.all
    end

    def show
        @board = Board.find_by_id(params[:id])
        @board_threads = order_threads(@board)
    end
    
end

app/helpers/boards_helper.rb
module BoardsHelper

    def last_post(thread)
        unless thread.posts.empty?
            post = thread.posts.last
            if post.user
                user = post.user.username
            else
                user = "DELETED USER"
            end
            "Last Post By #{link_to user, user_path(user), :class => "thread_links"} <br> #{display_full_date_time(post.created_at)}"
        end
    end

    def friendly_title(thread)
        if BoardThread.with_long_title.include?(thread)
            thread.title.truncate(20)
        else
            thread.title
        end
    end

end

app/views/boards/index.html.erb
<% @categories.each do |c| %>
    <div class="cat_header"><%= c.title %></div>
    <% c.boards.order(:title).each do |b| %>
        <div class="forum_tile">
            <%= link_to b.title, board_path(b), :class => "board_title" %>
            <div class="description">
                <%= b.description %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/boards/show.html.erb
<div class="nav_path">PATH: <%= link_to @board.category.title, boards_path, :class => 'links' %> >> <%= link_to @board.title, board_path(@board), :class => 'links' %></div>

<div class="main_header">
    <%= @board.title %>
</div>
<% @board_threads.each do |t| %>
    <div class="forum_tile">
        <%= "[LOCKED]" if t.locked %><%= link_to friendly_title(t), board_thread_path(t), :class => "board_title" %>
        <div class="thread_information">
            <%= last_post(t).html_safe%>
            <br><br>
            Total Posts: <%= t.posts.count %>
            <br><br>
        <% if admin? %>
            <%= link_to "Move Thread", edit_board_thread_path(t), :class => "thread_links" %>
            <%= link_to "Delete Thread", board_thread_path(t), :class => "thread_links", :method => :delete %>
        <% end %>
        </div>
    </div>

<% end %>
<div class="centered_button"><%= button_to "", new_board_thread_path, params: {board_id: @board.id}, :class => "create_thread_button", :method => :get %></div>