config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/github/callback' => 'sessions#create', via: [:get, :post]

  root to: 'static#home'
  get '/rules' => 'static#rules', as: 'rules'
  get '/admin' => 'admin#index'
  namespace "admin" do
    resources :categories
    resources :boards
    resources :static_pages, only: [:index, :edit, :update], param: :slug
    resources :users, only: [:index, :update], param: :slug
  end
  resources :boards, only: [:index, :show]
  resources :board_threads, only: [:show, :new, :create, :edit, :update, :destroy], :path => "threads"  do
    resources :posts, except: [:update]
    patch '/posts' => 'posts#update'
  end
  resources :users, param: :slug
  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  post '/session' => 'sessions#create', as: 'session'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/threads/:board_thread_id/lock' => 'board_threads#lock', as: 'lock'
  post '/karma' => 'users#karma', as: 'karma'
  post '/ban' => 'users#banned', as: 'banned'
  post '/search' => 'board_threads#search'

end

app/models/category.rb
class Category < ApplicationRecord
    validates :title, :presence => true,
                      :uniqueness => true

    has_many :boards, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(cat_params)
        if @category.save
            flash.notice = "Category successfully created!"
            redirect_to admin_categories_path
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find_by_id(params[:id])
    end

    def update
        @category = Category.find_by_id(params[:id])
        if @category.update(cat_params)
            flash.notice = "Category successfully updated!"
            redirect_to admin_categories_path
        else
            render 'edit'
        end
    end

    def destroy
        category = Category.find_by_id(params[:id])
        category.delete

        flash.notice = "Category deleted!"
        redirect_to admin_categories_path
    end

    private

    def cat_params
        params.require(:category).permit(:title)
    end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, category], :html => {class: 'form'} do |cat_form| %>
    <%= category_errors_display(category) %>
    <%= cat_form.text_field :title, :class => 'admin_fields', :placeholder => 'Input Unique Category Title' %>
    <div class="centered_button">
        <%= cat_form.submit "", :class => "#{chosen_class(category)}" %>
    </div>

<% end %>

app/views/admin/categories/edit.html.erb
<div class="nav_path">PATH: <%= link_to 'ADMIN PANEL', admin_path, :class => 'links' %> >> <%= link_to 'CATEGORIES CONTROLLER', admin_categories_path, :class => 'links' %> >> <%= link_to 'EDIT CATEGORY', edit_admin_category_path(@category), :class => 'links'%></div>
<div class="main_header">
    Edit Category
</div>
<%= render partial: 'form', locals: {category: @category} %>

app/views/admin/categories/index.html.erb
<div class="nav_path">PATH: <%= link_to 'ADMIN PANEL', admin_path, :class => 'links' %> >> <%= link_to 'CATEGORIES CONTROLLER', admin_categories_path, :class => 'links' %></div>
<div class="main_header">
    CATEGORIES CONTROLLER
</div>
<% @categories.each do |cat| %>
<div class="forum_tile">
    <%= link_to cat.title, boards_path, :class => 'board_title' %>
    <%= link_to "Edit", edit_admin_category_path(cat), :class => 'post_link', :method => :get  %>
    <%= link_to "Delete", admin_category_path(cat), :class => 'post_link', data: {confirm: "This action is irreversible and will delete the category and all boards and threads in this category. Are you sure this is what you want to do?"}, :method => :delete %>
    <Br>
    <p class='admin_desc'>Number of Boards:<%= cat.boards.count %></p>
</div>
<% end %>
<br>
<div class="forum_tile">
    <%= link_to "Create New Category", new_admin_category_path, :class => 'board_title' %>
</div>

app/views/admin/categories/new.html.erb
<div class="nav_path">PATH: <%= link_to 'ADMIN PANEL', admin_path, :class => 'links' %> >> <%= link_to 'CATEGORIES CONTROLLER', admin_categories_path, :class => 'links' %> >> <%= link_to 'NEW CATEGORY', new_admin_category_path, :class => 'links'%></div>
<div class="main_header">
    Create New Category
</div>
<%= render partial: 'form', locals: {category: @category} %>